# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.16.0
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 16.0
org_name: Odoo Community Association (OCA)
org_slug: qrtl
rebel_module_groups: []
repo_description: ''
repo_name: ''
repo_slug: ymd-oca
repo_website: https://www.quartile.co

